### PR TITLE
fix: Fix warnings when using Elixir 1.17

### PR DESCRIPTION
**Pull request by jfpedroza**

### CODE REVIEW

**Comment by randycoulman** [comment]
@jfpedroza Thanks for this PR! It looks like it will work to solve the issues, but it looks like there's a problem with CI. CircleCI hasn't release a Docker image with the tag `1.17` (yet?), so can't build on 1.17. I also note that they don't have any OTP 27.x images available yet.

Let me do some work on CI to make it possible to build on 1.17 and then I'll merge this. I'll try to get to this in the next few days.

**Comment by randycoulman** [comment]
Thanks again for the contribution! I'll get a new release out shortly containing this fix.

**Comment by jfpedroza** [comment]
Thanks!

**Comment by randycoulman** [comment]
Released as v2.1.0. Thanks again!

**Pull request merged**
